:-[aleph6].
:-read_all(train).
:-sat(1),tell('space1.txt'),reduce,told.
:-sat(2),tell('space2.txt'),reduce,told.
:-sat(3),tell('space3.txt'),reduce,told.
:-sat(4),tell('space4.txt'),reduce,told.
:-sat(5),tell('space5.txt'),reduce,told.
:-sat(6),tell('space6.txt'),reduce,told.
:-sat(7),tell('space7.txt'),reduce,told.
:-sat(8),tell('space8.txt'),reduce,told.
:-sat(9),tell('space9.txt'),reduce,told.
:-sat(10),tell('space10.txt'),reduce,told.
:-sat(11),tell('space11.txt'),reduce,told.
:-sat(12),tell('space12.txt'),reduce,told.
:-sat(13),tell('space13.txt'),reduce,told.
:-sat(14),tell('space14.txt'),reduce,told.
:-sat(15),tell('space15.txt'),reduce,told.
:-sat(16),tell('space16.txt'),reduce,told.
:-sat(17),tell('space17.txt'),reduce,told.
:-sat(18),tell('space18.txt'),reduce,told.
:-sat(19),tell('space19.txt'),reduce,told.
:-sat(20),tell('space20.txt'),reduce,told.
:-sat(21),tell('space21.txt'),reduce,told.
:-sat(22),tell('space22.txt'),reduce,told.
:-sat(23),tell('space23.txt'),reduce,told.
:-sat(24),tell('space24.txt'),reduce,told.
:-sat(25),tell('space25.txt'),reduce,told.
:-sat(26),tell('space26.txt'),reduce,told.
:-sat(27),tell('space27.txt'),reduce,told.
:-sat(28),tell('space28.txt'),reduce,told.
:-sat(29),tell('space29.txt'),reduce,told.
:-sat(30),tell('space30.txt'),reduce,told.
:-sat(31),tell('space31.txt'),reduce,told.
:-sat(32),tell('space32.txt'),reduce,told.
:-sat(33),tell('space33.txt'),reduce,told.
:-sat(34),tell('space34.txt'),reduce,told.
:-sat(35),tell('space35.txt'),reduce,told.
:-sat(36),tell('space36.txt'),reduce,told.
:-sat(37),tell('space37.txt'),reduce,told.
:-sat(38),tell('space38.txt'),reduce,told.
:-sat(39),tell('space39.txt'),reduce,told.
:-sat(40),tell('space40.txt'),reduce,told.
:-sat(41),tell('space41.txt'),reduce,told.
:-sat(42),tell('space42.txt'),reduce,told.
:-sat(43),tell('space43.txt'),reduce,told.
:-sat(44),tell('space44.txt'),reduce,told.
:-sat(45),tell('space45.txt'),reduce,told.
:-sat(46),tell('space46.txt'),reduce,told.
:-sat(47),tell('space47.txt'),reduce,told.
:-sat(48),tell('space48.txt'),reduce,told.
:-sat(49),tell('space49.txt'),reduce,told.
:-sat(50),tell('space50.txt'),reduce,told.
:-sat(51),tell('space51.txt'),reduce,told.
:-sat(52),tell('space52.txt'),reduce,told.
:-sat(53),tell('space53.txt'),reduce,told.
:-sat(54),tell('space54.txt'),reduce,told.
:-sat(55),tell('space55.txt'),reduce,told.
:-sat(56),tell('space56.txt'),reduce,told.
:-sat(57),tell('space57.txt'),reduce,told.
:-sat(58),tell('space58.txt'),reduce,told.
:-sat(59),tell('space59.txt'),reduce,told.
:-sat(60),tell('space60.txt'),reduce,told.
:-sat(61),tell('space61.txt'),reduce,told.
:-sat(62),tell('space62.txt'),reduce,told.
:-sat(63),tell('space63.txt'),reduce,told.
:-sat(64),tell('space64.txt'),reduce,told.
:-sat(65),tell('space65.txt'),reduce,told.
:-sat(66),tell('space66.txt'),reduce,told.
:-sat(67),tell('space67.txt'),reduce,told.
:-sat(68),tell('space68.txt'),reduce,told.
:-sat(69),tell('space69.txt'),reduce,told.
:-sat(70),tell('space70.txt'),reduce,told.
:-sat(71),tell('space71.txt'),reduce,told.
:-sat(72),tell('space72.txt'),reduce,told.
:-sat(73),tell('space73.txt'),reduce,told.
:-sat(74),tell('space74.txt'),reduce,told.
:-sat(75),tell('space75.txt'),reduce,told.
:-sat(76),tell('space76.txt'),reduce,told.
:-sat(77),tell('space77.txt'),reduce,told.
:-sat(78),tell('space78.txt'),reduce,told.
:-sat(79),tell('space79.txt'),reduce,told.
:-sat(80),tell('space80.txt'),reduce,told.
:-sat(81),tell('space81.txt'),reduce,told.
:-sat(82),tell('space82.txt'),reduce,told.
:-sat(83),tell('space83.txt'),reduce,told.
:-sat(84),tell('space84.txt'),reduce,told.
:-sat(85),tell('space85.txt'),reduce,told.
:-sat(86),tell('space86.txt'),reduce,told.
:-sat(87),tell('space87.txt'),reduce,told.
:-sat(88),tell('space88.txt'),reduce,told.
:-sat(89),tell('space89.txt'),reduce,told.
:-sat(90),tell('space90.txt'),reduce,told.
:-sat(91),tell('space91.txt'),reduce,told.
:-sat(92),tell('space92.txt'),reduce,told.
:-sat(93),tell('space93.txt'),reduce,told.
:-sat(94),tell('space94.txt'),reduce,told.
:-sat(95),tell('space95.txt'),reduce,told.
:-sat(96),tell('space96.txt'),reduce,told.
:-sat(97),tell('space97.txt'),reduce,told.
:-sat(98),tell('space98.txt'),reduce,told.
:-sat(99),tell('space99.txt'),reduce,told.
:-sat(100),tell('space100.txt'),reduce,told.
